-- AlterTable
ALTER TABLE "OrganizationRoleAssignment" ADD COLUMN "branchId" TEXT;

-- AlterTable
ALTER TABLE "ReferralCode" ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "displayName" TEXT,
ADD COLUMN "lastResetAt" TIMESTAMP(3),
ADD COLUMN "monthlyUseCount" INTEGER NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE "ReferralReward" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "referralCodeId" TEXT NOT NULL,
    "redemptionId" TEXT NOT NULL,
    "referrerUserId" TEXT NOT NULL,
    "rewardType" TEXT NOT NULL,
    "rewardValue" INTEGER NOT NULL,
    "appliedToSubId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "appliedAt" TIMESTAMP(3),
    "expiresAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ReferralReward_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OrgReferralPartnership" (
    "id" TEXT NOT NULL,
    "sourceOrgId" TEXT NOT NULL,
    "targetOrgId" TEXT NOT NULL,
    "referralPolicySnapshot" JSONB NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OrgReferralPartnership_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Offer" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "discountType" "CouponType" NOT NULL,
    "discountValue" INTEGER NOT NULL,
    "applicablePlans" JSONB,
    "startsAt" TIMESTAMP(3) NOT NULL,
    "endsAt" TIMESTAMP(3) NOT NULL,
    "maxRedemptions" INTEGER,
    "redemptionCount" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "stackable" BOOLEAN NOT NULL DEFAULT false,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Offer_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "OrganizationRoleAssignment_orgId_branchId_idx" ON "OrganizationRoleAssignment"("orgId", "branchId");

-- CreateIndex
CREATE INDEX "ReferralCode_orgId_status_idx" ON "ReferralCode"("orgId", "status");

-- CreateIndex
CREATE UNIQUE INDEX "ReferralReward_redemptionId_key" ON "ReferralReward"("redemptionId");

-- CreateIndex
CREATE INDEX "ReferralReward_orgId_referrerUserId_idx" ON "ReferralReward"("orgId", "referrerUserId");

-- CreateIndex
CREATE INDEX "ReferralReward_referralCodeId_idx" ON "ReferralReward"("referralCodeId");

-- CreateIndex
CREATE UNIQUE INDEX "OrgReferralPartnership_sourceOrgId_targetOrgId_key" ON "OrgReferralPartnership"("sourceOrgId", "targetOrgId");

-- CreateIndex
CREATE INDEX "OrgReferralPartnership_targetOrgId_status_idx" ON "OrgReferralPartnership"("targetOrgId", "status");

-- CreateIndex
CREATE INDEX "Offer_orgId_active_idx" ON "Offer"("orgId", "active");

-- CreateIndex
CREATE INDEX "Offer_orgId_startsAt_endsAt_idx" ON "Offer"("orgId", "startsAt", "endsAt");
