export const typography = {
  screenTitle: { fontSize: 26, fontFamily: "Inter_700Bold", letterSpacing: -0.4, lineHeight: 32 },
  headerTitle: { fontSize: 20, fontFamily: "Inter_600SemiBold", letterSpacing: -0.2, lineHeight: 26 },
  sectionTitle: { fontSize: 17, fontFamily: "Inter_600SemiBold", lineHeight: 22 },
  cardTitle: { fontSize: 15, fontFamily: "Inter_600SemiBold", lineHeight: 20 },
  body: { fontSize: 15, fontFamily: "Inter_400Regular", lineHeight: 21 },
  bodyStrong: { fontSize: 15, fontFamily: "Inter_600SemiBold", lineHeight: 21 },
  caption: { fontSize: 12.5, fontFamily: "Inter_600SemiBold", lineHeight: 16 },
  small: { fontSize: 13, fontFamily: "Inter_400Regular", lineHeight: 18 },
  metric: { fontSize: 28, fontFamily: "Inter_700Bold", fontVariant: ["tabular-nums" as "tabular-nums"], lineHeight: 32 },
  timer: { fontSize: 44, fontFamily: "Inter_800ExtraBold", fontVariant: ["tabular-nums" as "tabular-nums"], letterSpacing: 0, lineHeight: 50 },
  navLabel: { fontSize: 12, fontFamily: "Inter_600SemiBold", lineHeight: 15 },
  button: { fontSize: 14, fontFamily: "Inter_600SemiBold", lineHeight: 18 },
  display: { fontSize: 34, fontFamily: "Inter_700Bold", letterSpacing: -0.4, lineHeight: 39 },
  h1: { fontSize: 24, fontFamily: "Inter_600SemiBold", lineHeight: 30 },
  h2: { fontSize: 20, fontFamily: "Inter_600SemiBold", lineHeight: 26 },
  h3: { fontSize: 15, fontFamily: "Inter_600SemiBold", lineHeight: 20 },
  headline: { fontSize: 24, fontFamily: "Inter_600SemiBold", lineHeight: 30 },
  title: { fontSize: 20, fontFamily: "Inter_600SemiBold", letterSpacing: -0.2, lineHeight: 26 },
  titleSmall: { fontSize: 15, fontFamily: "Inter_600SemiBold", lineHeight: 20 },
  eyebrow: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0,
    textTransform: "uppercase" as const,
  },
};
