"use client";

import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, QrCode, RefreshCcw, ShieldCheck } from "lucide-react";
import QRCode from "qrcode";
import { GlassCard, Pill } from "./glass-card";
import { webApiFetch } from "@/lib/api-client";

export function AttendanceQrPanel({
  orgId,
  branchId,
  branchName,
}: {
  orgId: string;
  branchId?: string | null;
  branchName?: string | null;
}) {
  const [qrPayload, setQrPayload] = useState<string>("");
  const [checkInCode, setCheckInCode] = useState<string>("");
  const [qrImageUrl, setQrImageUrl] = useState<string>("");
  const [expiresAt, setExpiresAt] = useState<string>("");
  const [error, setError] = useState<string>("");
  const [qrRenderError, setQrRenderError] = useState<string>("");

  const loadToken = useCallback(async () => {
    try {
      setError("");
      const query = branchId ? `?branchId=${encodeURIComponent(branchId)}` : "";
      const payload = await webApiFetch<{
        qrPayload: string;
        checkInCode?: string;
        expiresAt: string;
      }>(
        `/api/orgs/${orgId}/attendance/qr-token${query}`,
        { method: "POST" },
      );
      setQrPayload(payload.qrPayload);
      setCheckInCode(payload.checkInCode ?? "");
      setExpiresAt(payload.expiresAt);
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Unable to load attendance QR token.");
    }
  }, [branchId, orgId]);

  useEffect(() => {
    void loadToken();
    const timer = window.setInterval(() => {
      void loadToken();
    }, 120_000);
    return () => window.clearInterval(timer);
  }, [loadToken]);

  useEffect(() => {
    if (!qrPayload) {
      setQrImageUrl("");
      return;
    }

    let active = true;
    setQrRenderError("");
    void QRCode.toDataURL(qrPayload, {
      errorCorrectionLevel: "M",
      margin: 2,
      width: 280,
      color: {
        dark: "#070908",
        light: "#f6ffe2",
      },
    })
      .then((dataUrl) => {
        if (active) {
          setQrImageUrl(dataUrl);
        }
      })
      .catch(() => {
        if (active) {
          setQrRenderError("Unable to show the QR image. Refresh and try again.");
        }
      });

    return () => {
      active = false;
    };
  }, [qrPayload]);

  return (
    <GlassCard variant="strong">
      <div className="flex items-center justify-between gap-3">
        <div>
          <h2 className="text-xl font-semibold">Attendance</h2>
          <p className="mt-1 text-sm text-white/45">
            Scan the QR code to mark attendance for {branchName ?? "this branch"}.
          </p>
        </div>
        <button
          onClick={() => void loadToken()}
          className="zook-focus inline-flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm text-white/70"
        >
          <RefreshCcw size={16} />
          Refresh
        </button>
      </div>
      <div className="mt-5 rounded-[28px] border border-white/10 bg-black/30 p-5">
        <div className="flex items-center gap-2 text-lime-200">
          <QrCode size={18} />
          <span className="text-sm font-medium">Live Attendance QR</span>
        </div>
        {error ? <p className="mt-4 text-sm text-red-200">{error}</p> : null}
        {!error ? (
          <div className="mt-4 grid gap-5 lg:grid-cols-[300px_1fr]">
            <div className="grid min-h-[300px] place-items-center rounded-[26px] border border-lime-200/25 bg-lime-50 p-4 shadow-[0_18px_46px_rgba(185,244,85,0.18),inset_0_1px_0_rgba(255,255,255,0.45)]">
              {qrImageUrl ? (
                <img
                  src={qrImageUrl}
                  alt="Attendance QR code"
                  className="h-full max-h-[280px] w-full max-w-[280px] rounded-xl"
                />
              ) : (
                <p className="text-center text-sm font-medium text-black/60">
                  {qrPayload ? "Rendering QR..." : "Loading QR..."}
                </p>
              )}
            </div>
            <div className="flex min-w-0 flex-col justify-between gap-4">
              <div>
                <p className="text-sm leading-6 text-white/58">
                  Display this at reception or the entry gate. Members can scan the QR or type the
                  short code in the mobile app. The token is generated by the server and refreshes
                  automatically every 120 seconds in this console.
                </p>
                <div className="mt-5 rounded-2xl border border-lime-200/20 bg-lime-200/10 p-4">
                  <p className="text-xs font-semibold uppercase tracking-[0.18em] text-lime-100/70">
                    Rolling signed QR token
                  </p>
                  <p className="mt-2 font-mono text-4xl font-black tracking-[0.14em] text-lime-100">
                    {checkInCode || "-- ----"}
                  </p>
                  <p className="mt-2 text-sm leading-5 text-white/48">
                    Short entry code uses the same branch and expiry as the QR.
                  </p>
                </div>
                {qrRenderError ? (
                  <p className="mt-3 text-sm text-red-200">{qrRenderError}</p>
                ) : null}
              </div>
              <div className="flex flex-wrap gap-2">
                <Pill tone="lime">Check-in ready</Pill>
                {branchName ? <Pill>{branchName}</Pill> : null}
                {expiresAt ? <Pill>Expires {new Date(expiresAt).toLocaleTimeString()}</Pill> : null}
              </div>
              <div className="rounded-2xl border border-white/10 bg-black/35 p-4">
                <div className="flex items-center gap-2 text-sm font-medium text-white/72">
                  <ShieldCheck className="h-4 w-4 text-lime-200" aria-hidden="true" />
                  Validation checklist
                </div>
                <div className="mt-3 grid gap-2 text-sm text-white/52">
                  {[
                    "Server-authoritative validation",
                    "Replay protection",
                    "Branch check",
                    "Membership check",
                  ].map((item) => (
                    <div key={item} className="flex items-center gap-2">
                      <CheckCircle2 className="h-4 w-4 text-lime-200" aria-hidden="true" />
                      {item}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        ) : null}
      </div>
    </GlassCard>
  );
}
