export const deskTranslations = {
  en: {
    common: {
      language: "Language",
      english: "English",
      hindi: "Hindi",
      signOut: "Sign out",
      signingOut: "Signing out...",
    },
    tabs: { queue: "Queue", member: "Member", payment: "Payment", pickup: "Pickup" },
    mainBranch: "Main branch",
    checkInsToday: "check-ins today",
    todayQueue: "Today's queue",
    queueDescription: "Review flagged entries and keep the check-in line moving.",
    pending: "pending",
    member: "Member",
    membership: "Membership",
    branch: "branch",
    approve: "Approve",
    reject: "Reject",
    noReview: "No entries need review right now.",
    recentCheckIns: "Recent check-ins",
    noCheckIns: "No check-ins yet today.",
    findMember: "Find a member",
    searchPlaceholder: "Search by name, phone, or email",
    phoneEnding: "Phone ending",
    noActivePlan: "No active plan",
    profilePhotoMissing: "Profile photo not added yet.",
    noActiveMembership: "No active membership",
    validUntil: "Valid until",
    recentActivity: "Recent activity",
    lastCheckIn: "Last check-in",
    lastPayment: "Last payment",
    selectMember: "Select a member to see membership status and quick actions.",
    overrideEntry: "Override entry",
    sendMemberMessage: "Send update",
    directMessagePrompt: "Message for this member",
    deskMessageTitle: "Update from the desk",
    messageSent: "Message sent.",
    unableMessage: "Unable to send message.",
    recordPayment: "Record payment",
    paymentDescription: "Use this for cash, UPI, card, or bank transfer collected at the desk.",
    paymentPurpose: "What is this for?",
    membershipPayment: "Membership",
    shopOrderPayment: "Shop order",
    otherPayment: "Other",
    chooseMember: "Choose member",
    chooseOrder: "Choose order",
    noPayAtDeskOrders: "No shop orders are waiting for desk payment.",
    plan: "Plan",
    renewExisting: "Renew existing subscription",
    mode: "Mode",
    amount: "Amount",
    reason: "Reason",
    reasonPlaceholder: "What was collected?",
    referenceNumber: "Reference number",
    referencePlaceholder: "UPI ref or receipt number",
    notes: "Notes",
    recording: "Recording...",
    receiptReady: "Receipt ready",
    receiptFor: "For",
    receiptAmount: "Amount",
    receiptMode: "Mode",
    receiptReference: "Reference",
    receiptDate: "Date",
    notAdded: "Not added",
    printReceipt: "Print receipt",
    shopPickup: "Shop pickup",
    pickupDescription: "Verify pickup codes and mark ready orders fulfilled.",
    payAtDesk: "Pay at desk",
    paid: "Paid",
    pickupCode: "Pickup code",
    fulfilledToday: "fulfilled today",
    codeVerified: "Code verified",
    codeSkipped: "Code skipped",
    verifyCode: "Verify code",
    skipCode: "Skip code",
    markFulfilled: "Mark fulfilled",
    noPickupOrders: "No pickup orders are waiting right now.",
    showEntryQr: "Show entry QR",
    entryApproved: "Entry approved.",
    entryRejected: "Entry rejected.",
    unableEntry: "Unable to update entry.",
    paymentRecorded: "Payment recorded. Receipt amount:",
    unablePayment: "Unable to record payment.",
    shopPaymentRecorded: "Shop payment recorded. Receipt amount:",
    unableShopPayment: "Unable to record shop payment.",
    pickupVerified: "Pickup code verified.",
    unablePickupVerify: "Unable to verify pickup code.",
    pickupFulfilled: "Pickup marked fulfilled.",
    unablePickup: "Unable to fulfill pickup.",
    pickupPrompt: "Enter the pickup code shown by the member",
  },
  hi: {
    common: {
      language: "भाषा",
      english: "अंग्रेज़ी",
      hindi: "हिन्दी",
      signOut: "साइन आउट",
      signingOut: "साइन आउट हो रहा है...",
    },
    tabs: { queue: "लाइन", member: "मेंबर", payment: "पेमेंट", pickup: "पिकअप" },
    mainBranch: "मुख्य ब्रांच",
    checkInsToday: "आज check-ins",
    todayQueue: "आज की लाइन",
    queueDescription: "Flagged entries देखें और check-in line smoothly चलाएं.",
    pending: "pending",
    member: "मेंबर",
    membership: "मेंबरशिप",
    branch: "ब्रांच",
    approve: "Approve करें",
    reject: "Reject करें",
    noReview: "अभी review के लिए कोई entry नहीं है.",
    recentCheckIns: "Recent check-ins",
    noCheckIns: "आज अभी कोई check-in नहीं हुआ.",
    findMember: "मेंबर ढूंढें",
    searchPlaceholder: "नाम, फोन या ईमेल से खोजें",
    phoneEnding: "फोन ending",
    noActivePlan: "Active plan नहीं है",
    profilePhotoMissing: "Profile photo अभी add नहीं है.",
    noActiveMembership: "Active membership नहीं है",
    validUntil: "Valid until",
    recentActivity: "Recent activity",
    lastCheckIn: "Last check-in",
    lastPayment: "Last payment",
    selectMember: "Membership status और quick actions देखने के लिए member चुनें.",
    overrideEntry: "Entry override करें",
    sendMemberMessage: "Update भेजें",
    directMessagePrompt: "इस member के लिए message",
    deskMessageTitle: "Desk से update",
    messageSent: "Message भेज दिया गया.",
    unableMessage: "Message नहीं भेज पाया.",
    recordPayment: "Payment record करें",
    paymentDescription: "Desk पर cash, UPI, card या bank transfer collect करने के लिए.",
    paymentPurpose: "Payment किस लिए है?",
    membershipPayment: "Membership",
    shopOrderPayment: "Shop order",
    otherPayment: "Other",
    chooseMember: "Member चुनें",
    chooseOrder: "Order चुनें",
    noPayAtDeskOrders: "Desk payment के लिए कोई shop order waiting में नहीं है.",
    plan: "Plan",
    renewExisting: "Existing subscription renew करें",
    mode: "Mode",
    amount: "Amount",
    reason: "Reason",
    reasonPlaceholder: "क्या collect किया गया?",
    referenceNumber: "Reference number",
    referencePlaceholder: "UPI ref या receipt number",
    notes: "Notes",
    recording: "Recording...",
    receiptReady: "Receipt ready",
    receiptFor: "For",
    receiptAmount: "Amount",
    receiptMode: "Mode",
    receiptReference: "Reference",
    receiptDate: "Date",
    notAdded: "Add नहीं है",
    printReceipt: "Receipt print करें",
    shopPickup: "Shop pickup",
    pickupDescription: "Pickup code verify करें और ready orders fulfill करें.",
    payAtDesk: "Desk पर pay",
    paid: "Paid",
    pickupCode: "Pickup code",
    fulfilledToday: "आज fulfilled",
    codeVerified: "Code verified",
    codeSkipped: "Code skipped",
    verifyCode: "Code verify करें",
    skipCode: "Code skip करें",
    markFulfilled: "Fulfilled mark करें",
    noPickupOrders: "अभी कोई pickup order waiting में नहीं है.",
    showEntryQr: "Entry QR दिखाएं",
    entryApproved: "Entry approve हो गई.",
    entryRejected: "Entry reject हो गई.",
    unableEntry: "Entry update नहीं हो पाई.",
    paymentRecorded: "Payment record हो गया. Receipt amount:",
    unablePayment: "Payment record नहीं हो पाया.",
    shopPaymentRecorded: "Shop payment record हो गया. Receipt amount:",
    unableShopPayment: "Shop payment record नहीं हो पाया.",
    pickupVerified: "Pickup code verify हो गया.",
    unablePickupVerify: "Pickup code verify नहीं हो पाया.",
    pickupFulfilled: "Pickup fulfilled mark हो गया.",
    unablePickup: "Pickup fulfill नहीं हो पाया.",
    pickupPrompt: "Member का pickup code enter करें",
  },
} as const;

type StringLeaves<T> = {
  readonly [K in keyof T]: T[K] extends string ? string : StringLeaves<T[K]>;
};

export type DeskCopy = StringLeaves<(typeof deskTranslations)["en"]>;
