export const deskTranslations = {
  en: {
    common: {
      account: "Account",
      language: "Language",
      english: "English",
      hindi: "Hindi",
      signOut: "Sign out",
      signingOut: "Signing out...",
      cancel: "Cancel",
      switchOrganization: "Switch organization",
    },
    backToManagement: "Back to Management",
    openedAsReception: "You are signed in as Reception, so Zook opened Reception Desk.",
    tabs: { queue: "Queue", member: "Member", payment: "Payment", pickup: "Pickup" },
    mainBranch: "Main branch",
    checkInsToday: "check-ins today",
    todayQueue: "Today's queue",
    queueDescription: "Review flagged entries and keep the check-in line moving.",
    pending: "pending",
    member: "Member",
    privateId: "Private ID",
    photoMatches: "Photo matches",
    verifyPhoto: "Verify photo",
    membership: "Membership",
    branch: "branch",
    approve: "Approve",
    reject: "Reject",
    noReview: "No entries need review.",
    recentCheckIns: "Recent check-ins",
    noCheckIns: "No check-ins yet today.",
    findMember: "Find a member",
    searchPlaceholder: "Search by name, phone, or email",
    phoneEnding: "Phone ending",
    noActivePlan: "No active plan",
    profilePhotoMissing: "Profile photo not added yet.",
    noActiveMembership: "No active membership",
    validUntil: "Valid until",
    recentActivity: "Recent activity",
    activeCheckIn: "Active check-in",
    checkOut: "Check out",
    lastCheckIn: "Last check-in",
    lastPayment: "Last payment",
    selectMember: "Select a member to see membership status and actions.",
    overrideEntry: "Override entry",
    sendMemberMessage: "Send update",
    directMessagePrompt: "Message for this member",
    deskMessageTitle: "Update from the desk",
    messageSent: "Message sent.",
    unableMessage: "Unable to send message.",
    recordPayment: "Record payment",
    paymentDescription: "Cash, UPI, card, or bank transfer collected at the desk.",
    paymentPurpose: "What is this for?",
    membershipPayment: "Membership",
    shopOrderPayment: "Shop order",
    otherPayment: "Other",
    chooseMember: "Choose member",
    chooseOrder: "Choose order",
    noPayAtDeskOrders: "No shop orders are waiting for desk payment.",
    plan: "Plan",
    renewExisting: "Renew existing subscription",
    mode: "Mode",
    amount: "Amount",
    reason: "Reason",
    reasonPlaceholder: "What was collected?",
    referenceNumber: "Reference number",
    referencePlaceholder: "UPI ref or receipt number",
    proofFileId: "Proof file ID",
    proofPlaceholder: "Optional uploaded payment proof",
    notes: "Notes",
    recording: "Recording...",
    receiptReady: "Receipt generated",
    receiptFor: "For",
    receiptAmount: "Amount",
    receiptMode: "Mode",
    receiptReference: "Reference",
    receiptDate: "Date",
    notAdded: "Not added",
    printReceipt: "Print receipt",
    shopPickup: "Shop pickup",
    pickupDescription: "Verify pickup codes and mark pickup orders fulfilled.",
    payAtDesk: "Pay at desk",
    paid: "Paid",
    pickupCode: "Pickup code",
    fulfilledToday: "fulfilled today",
    codeVerified: "Code verified",
    codeSkipped: "Code skipped",
    verifyCode: "Verify code",
    skipCode: "Skip code",
    markFulfilled: "Mark fulfilled",
    noPickupOrders: "No pickup orders waiting.",
    showEntryQr: "Show check-in QR",
    entryApproved: "Entry approved.",
    entryCheckedOut: "Checked out.",
    entryRejected: "Entry rejected.",
    unableEntry: "Unable to update entry.",
    paymentRecorded: "Payment recorded. Receipt amount:",
    unablePayment: "Unable to record payment.",
    shopPaymentRecorded: "Shop payment recorded. Receipt amount:",
    unableShopPayment: "Unable to record shop payment.",
    pickupVerified: "Pickup code verified.",
    unablePickupVerify: "Unable to verify pickup code.",
    pickupFulfilled: "Pickup marked fulfilled.",
    unablePickup: "Unable to fulfill pickup.",
    pickupPrompt: "Enter the pickup code shown by the member",
    sending: "Sending...",
    verifying: "Verifying...",
    recentPayments: "Recent payments",
    recentPaymentsDescription: "Look up recent payments and refund within 24 hours.",
    noRecentPayments: "No recent payments yet.",
    loadingRecentPayments: "Loading recent payments...",
    unableRecentPayments: "Unable to load recent payments.",
    refund: "Refund",
    refunding: "Refunding...",
    refunded: "Refunded",
    partiallyRefunded: "Partially refunded",
    refundReason: "Reason for refund",
    refundReasonPlaceholder: "Why is this payment being refunded?",
    refundConfirmTitle: "Refund this payment?",
    refundConfirmDescription:
      "This sends the refund to the payment partner when a reference exists and cannot be undone.",
    submitRefund: "Submit refund",
  },
  hi: {
    common: {
      account: "खाता",
      language: "भाषा",
      english: "अंग्रेज़ी",
      hindi: "हिन्दी",
      signOut: "साइन आउट",
      signingOut: "साइन आउट हो रहा है...",
      cancel: "रद्द करें",
      switchOrganization: "Organization बदलें",
    },
    backToManagement: "Management पर वापस जाएं",
    openedAsReception: "आप Reception के रूप में signed in हैं, इसलिए Zook ने Reception Desk खोला.",
    tabs: { queue: "लाइन", member: "मेंबर", payment: "पेमेंट", pickup: "पिकअप" },
    mainBranch: "मुख्य ब्रांच",
    checkInsToday: "आज check-ins",
    todayQueue: "आज की लाइन",
    queueDescription: "Flagged entries देखें और check-in line smoothly चलाएं.",
    pending: "pending",
    member: "मेंबर",
    privateId: "Private ID",
    photoMatches: "Photo matches",
    verifyPhoto: "Photo verify करें",
    membership: "मेंबरशिप",
    branch: "ब्रांच",
    approve: "Approve करें",
    reject: "Reject करें",
    noReview: "अभी review के लिए कोई entry नहीं है.",
    recentCheckIns: "Recent check-ins",
    noCheckIns: "आज अभी कोई check-in नहीं हुआ.",
    findMember: "मेंबर ढूंढें",
    searchPlaceholder: "नाम, फोन या ईमेल से खोजें",
    phoneEnding: "फोन ending",
    noActivePlan: "Active plan नहीं है",
    profilePhotoMissing: "Profile photo अभी add नहीं है.",
    noActiveMembership: "Active membership नहीं है",
    validUntil: "Valid until",
    recentActivity: "Recent activity",
    activeCheckIn: "Active check-in",
    checkOut: "Check out",
    lastCheckIn: "Last check-in",
    lastPayment: "Last payment",
    selectMember: "Membership status और actions देखने के लिए member चुनें.",
    overrideEntry: "Entry override करें",
    sendMemberMessage: "Update भेजें",
    directMessagePrompt: "इस member के लिए message",
    deskMessageTitle: "Desk से update",
    messageSent: "Message भेज दिया गया.",
    unableMessage: "Message नहीं भेज पाया.",
    recordPayment: "Payment record करें",
    paymentDescription: "Desk पर cash, UPI, card या bank transfer collect करने के लिए.",
    paymentPurpose: "Payment किस लिए है?",
    membershipPayment: "Membership",
    shopOrderPayment: "Shop order",
    otherPayment: "Other",
    chooseMember: "Member चुनें",
    chooseOrder: "Order चुनें",
    noPayAtDeskOrders: "Desk payment के लिए कोई shop order waiting में नहीं है.",
    plan: "Plan",
    renewExisting: "Existing subscription renew करें",
    mode: "Mode",
    amount: "Amount",
    reason: "Reason",
    reasonPlaceholder: "क्या collect किया गया?",
    referenceNumber: "Reference number",
    referencePlaceholder: "UPI ref या receipt number",
    proofFileId: "Proof file ID",
    proofPlaceholder: "Optional uploaded payment proof",
    notes: "Notes",
    recording: "Recording...",
    receiptReady: "Receipt generated",
    receiptFor: "For",
    receiptAmount: "Amount",
    receiptMode: "Mode",
    receiptReference: "Reference",
    receiptDate: "Date",
    notAdded: "Add नहीं है",
    printReceipt: "Receipt print करें",
    shopPickup: "Shop pickup",
    pickupDescription: "Pickup code verify करें और pickup orders fulfill करें.",
    payAtDesk: "Desk पर pay",
    paid: "Paid",
    pickupCode: "Pickup code",
    fulfilledToday: "आज fulfilled",
    codeVerified: "Code verified",
    codeSkipped: "Code skipped",
    verifyCode: "Code verify करें",
    skipCode: "Code skip करें",
    markFulfilled: "Fulfilled mark करें",
    noPickupOrders: "अभी कोई pickup order waiting में नहीं है.",
    showEntryQr: "Check-in QR दिखाएं",
    entryApproved: "Entry approve हो गई.",
    entryCheckedOut: "Check-out हो गया.",
    entryRejected: "Entry reject हो गई.",
    unableEntry: "Entry update नहीं हो पाई.",
    paymentRecorded: "Payment record हो गया. Receipt amount:",
    unablePayment: "Payment record नहीं हो पाया.",
    shopPaymentRecorded: "Shop payment record हो गया. Receipt amount:",
    unableShopPayment: "Shop payment record नहीं हो पाया.",
    pickupVerified: "Pickup code verify हो गया.",
    unablePickupVerify: "Pickup code verify नहीं हो पाया.",
    pickupFulfilled: "Pickup fulfilled mark हो गया.",
    unablePickup: "Pickup fulfill नहीं हो पाया.",
    pickupPrompt: "Member का pickup code enter करें",
    sending: "भेजा जा रहा है...",
    verifying: "Verify हो रहा है...",
    recentPayments: "Recent payments",
    recentPaymentsDescription: "Recent payments देखें और 24 घंटे के अंदर refund करें.",
    noRecentPayments: "अभी कोई recent payment नहीं है.",
    loadingRecentPayments: "Recent payments load हो रहे हैं...",
    unableRecentPayments: "Recent payments load नहीं हो पाए.",
    refund: "Refund",
    refunding: "Refund हो रहा है...",
    refunded: "Refunded",
    partiallyRefunded: "Partially refunded",
    refundReason: "Refund का reason",
    refundReasonPlaceholder: "यह payment क्यों refund हो रहा है?",
    refundConfirmTitle: "यह payment refund करें?",
    refundConfirmDescription:
      "Reference होने पर यह refund payment partner को भेजा जाता है और इसे undo नहीं किया जा सकता.",
    submitRefund: "Refund submit करें",
  },
} as const;

type StringLeaves<T> = {
  readonly [K in keyof T]: T[K] extends string ? string : StringLeaves<T[K]>;
};

export type DeskCopy = StringLeaves<(typeof deskTranslations)["en"]>;
