ALTER TABLE "Branch"
ADD COLUMN IF NOT EXISTS "qrMode" TEXT NOT NULL DEFAULT 'ROLLING',
ADD COLUMN IF NOT EXISTS "staticQrExpiryDays" INTEGER NOT NULL DEFAULT 30;

ALTER TYPE "AttendanceSource" ADD VALUE IF NOT EXISTS 'AUTO_CHECKOUT';

ALTER TABLE "Organization"
ADD COLUMN IF NOT EXISTS "allowSelfServePause" BOOLEAN NOT NULL DEFAULT true;
